spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: qewr
    username: postgres
    url: jdbc:postgresql://localhost/orders
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  kafka:
    consumer:
      group-id: order-service-group
    bootstrap-servers: localhost:9092


server:
  port: 8082

payment-service:
  base-url: http://localhost:8085
order-paid-topic: orders.events
delivery-assigned-topic: delivery.events