spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: qewr
    username: postgres
    url: jdbc:postgresql://localhost/orders
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  kafka:
    consumer:
      group-id: delivery-service-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.example.api.kafka"
    bootstrap-servers: localhost:9092


server:
  port: 8084

order-paid-topic: orders.events
delivery-assigned-topic: delivery.events