spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: qewr
    username: postgres
    url: jdbc:postgresql://localhost/orders
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    consumer:
      group-id: delivery-service-group
    bootstrap-servers: localhost:9092


server:
  port: 8084

order-paid-topic: orders.events
delivery-assigned-topic: delivery.events